baseURL: "https://stopcovid19-ichikawa.netlify.app/"
defaultContentLanguage: ja
defaultContentLanguageInSubdir: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: G-6SX4L2MEKS
hasCJKLanguage: true

author:
  name: Meiryo7743

disableKinds:
  - RSS
  - section
  - taxonomyTerm
  - term

languages:
  ja:
    languageCode: ja
    languageName: 日本語
    params:
      description: 当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）及びそれに関連する情報を提供いたします。当サイトは個人が制作した非公式サイトです。
      ogp: "/img/ogp.ja.png"
      notice:
        emergency: false
        translate: false
    title: 【非公式】市川市新型コロナウイルス感染症情報サイト
    weight: 10
  # ja-hrkt:
  #   languageCode: ja
  #   languageName: やさしいにほんご
  #   params:
  #     description: 当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）及びそれに関連する情報を提供いたします。当サイトは個人が制作した非公式サイトです。
  #     ogp: "/img/ogp.ja.png"
  #     notice:
  #       emergency: false
  #       translate: true
  #   title: 【ひこうしき】 いちかわし 新型コロナウイルス かんせんしょう じょうほう サイト
  #   weight: 11
  en:
    languageCode: en
    languageName: English
    params:
      description: This site provides the latest information on COVID-19 in Ichikawa. Note that it is unofficial website developed by individual.
      ogp: "/img/ogp.en.png"
      notice:
        emergency: false
        translate: true
    title: "[UNOFFICIAL] Ichikawa COVID-19 Information Site"
    weight: 20

markup:
  goldmark:
    renderer:
      unsafe: false

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepEndTags: false

outputs:
  home:
    - HTML
  page:
    - HTML

params:
  copyrightYear: 2020
  favicon:
    # apple-touch-icon
    - {
        rel: apple-touch-icon,
        sizes: 180x180,
        href: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0BAMAAADP4xsBAAAAGFBMVEUAAABaxfRbxPJcw/NbxPT9/v6w3fhdxPTY2wbOAAAABXRSTlMAMHmn355KSKQAAATHSURBVHja7ZtLbutGEEVJKgsgIANvqiAGPBWTgcbUhCsgtQKqp474qe3HSSTdNC5axf4h7wGvRoItH15Xn66mDar4WT/re6/ykA39MdeZyO8iUx72m3zVlIO8l3/qlp5cyb3a5OidPKrJ0JBHHTIs473m9OyPBzuD3qc7OoPe5Rc7l4JV92Cf07NzKsjsP+q0CkLvj+jGV49s77aCb9F7v+xu0BsK3hvURGp3JgWn52Q5Rm7E9sGGgs9XYUuJ/jakNzSPNe6ACWvVFEWGFPhS9EipCAK9gwchFg1stD9qfEM11I3aPUXOaFSLLsVNWGxrzCXS7xw5jPZ4SV1qYrQ7/vcyv1KXjpGD/wMo6tIh6rhCG6CdNWF9hYYCzD5aE9ZbaPwUidHY74q8oalI8BJd8xKa9/Ev2Ch0tTbs5pG7PfOEbfzIDXWJJ+wmBZVf8p3GtMc9rHtpgADbveR7VTvqkl1nl6j72eteF136vbP6xdtrJ7OiXe3oki0FD4WqIzStiePe2pKCR9nfIeaXchxfdYkD4GonIbS9ARpXl0gK8seJ7kg7Csm/Bi7fudFoqOO04ebT1dzozqldY58UrPf8Es1CQ2PHQKkhqIb+8/Vpw1MpDM3bnmcp3uqD5tOPu+SxjPKpnDY0HPFWNfX202Yi91W0ftqgS3jraDR0u/W0mWvL/bU3auqtp83BXtV+M/qbJnRjr+q4Af0JtLB2LqH7r5LNqTs01DE6sKqrH1rmV6eNvarLJnR7Ryunjd370Ss1aUeHC8jSe6OPL08brOoC9FZDjvocRejBL7Wu3dOP3vij9Tm6bES3hNbn6BiaWp+jS4AhyhxFan9DFO2sZbyEpD51PEcptC8a/eA5iurhtWYIo2d8h//yXYAOSc1zFHXt/61QdGfNUdQqsm5N/elIDe0s8HhvSPgyAr2DGOO1l15kTYSubJuX3sgabgjQ0A5iPF/0Jjw1tLM3yghDgtHQDuhhHXr0OtyQUgiNCl5GRtvg62pyoQXlNiQYnSn1kBK9EjqZIUu21CuZlwKN0CiTxhCERkm61Es+tFxHf/RnkHySbcsM+dBGcs2QQbKlvuRDG0lvCMh5Jt8gidELhU5myAh06tRAi4gxedCmH1OdMoz+qjzLuKZGy0joWENY7AWaRKXm2MOYHr2ONEYiDeHc6VKjlv8ZXdZ+hkASHX0LSS1AX2QcHGg5x6HN2jvQlUjjYQgrchn7qyu1SBOUmrvNqUV+i0IPvTu1SIghKAXt7TXK1esqHm1ESe0/Q5A5ZUO2Tb63jWh9n/MzBu/+hiw6GQCv1Gj1RXmkqDz5ohFaexCq7LwMQasH/Wm2qvM7dhFaf+Jn54VG6C0PcuwVtBLaIpOC/n8VXBzasYK+d6rD5kd9ysbzPwsGQqu1Cc1rOBWRaA4NoROh6WQBORINPaBdarSBdpFoajXIydDDOKIf5yIhujciT/TN/8FaN3q93vttoJ1HVVtOGQPtfGqnomUNfSp4r6AhtH9909FNEVi1hm6L4HKjIXQW9FTkQk91HjSEToiGdunR0C6+TkCTdulTnxN+5AlozNEk7A5oaJemKqChXaLaAZ38w3FvQB+LDFVC6BzotsiDhnbp0VORCz3VP+BHjr+b+gsDxIUZ7S+5eAAAAABJRU5ErkJggg==",
      }

    # SVG favicon
    - { rel: icon, type: "image/svg+xml", href: "/img/logo.svg" }

    # Alternate favicon
    - {
        rel: icon alternate,
        type: "image/png",
        sizes: 512x512,
        href: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIABAMAAAAGVsnJAAAAFVBMVEUAAABZv/JdxPJbw/P+/v604Pldw/SOF+0MAAAABHRSTlMAKHmuSl49kgAADq1JREFUeNrtnUFu4zwShSUGmLWmBWTtRgNcT3oAnYDSCWjtY0t1/yP8SPynaXcsFukS5SJLb91JXJ+f+KooSl3t2rVr165du3bt2rVr165du3bt2rVr166UUr8r0ao7eKsEq+4A4GclVxo+dKik6hU+dW4qmWoBRBN4gT86VQKlAEQTUB1cSV4Y1h2AZAK1hisJDEMNIJpAC1cSGIYtgGgCCq4kMAwVOImMAgXSCbSwIDGz8R8CYsNQAwCIjgLxBOoOQHYYqp2A+DB8EU9gD8NXTxTIILCHoS8KdgKVBPnC8L2SoL0d2MNwJyA+DHcCexjus/Eehu1DBNqC4DwShm1ROamjZ2NVWKcQG4aqKywnI2fjuiuuU4hqB2qdc0429DDUOY/N+kRuB9qcO4UW4I0Yhm3OvVLr+8i/ggionMdm5T7yo2Goch4aVQd+Ah1KoO4yHpvrDvnIeBjWXca76LVGvjRkNv79cZHkPDZruNJjYahzHptb7EvDw/D/OW8ctOhHxgnkvHOiwj+zFlJ/fDuQ8d5h3cWcA6g7GfVHtgM53z/QsecAlJD6I9qBnO8htvDAOYBWSP2edqDoAIwMw5xPkqjuYQ93JQdgVBhmfJqs1pQcU0UHYHAY5nyitKX2sm3RARg0GWYdAPR5VuV8BaD1435WXcZrIBpieDV1l3EXgNePEqh1zn2QBvK2js55EngFoBJoc56FWiBv7bY5T8Otr8g2iIDKeT9AwbJ+h50DUDnviKFnXzVKoO4y3hOssXvc+DmAust4V7xGqsMZxWcoqxdTov7GzwHonO+MBZ50Uo/cA87h5RtYxsXFXH43BxRSP7FX6mBZLKJAIUs1kcCJ+wNG3qWNPi+duD9ghIQblcC54f6IVZw/4/s97g8YIQ0AlcCB+yNWSANA3Tf8yf1p2+AGgH4P+BdHAsirAKgE3rk/bUtYnHX8uFd33AiQPpEOCADuzxsjnoylh/8KxWs2Rh57JBI4H7g/b0zKJTwMD9xfTIkEIPUuwon7yzcQM9Id8JP3qycCJmDqKnjgTCAkkOgpwPflG2ENAL0PYPvyDZ2yfqcT15dvBI4l9FngxPPFlG3y+l01HMOwXSUAiQR++VrIzBuAlGFYs3j/Udye4GHFIKq7hkEAIvWnbAc0kOtfJwAJBCiz8StAk3ALuCGsoYnbAfeX8wlA6gNGP+83D82zA/AHIErSDji/cA5A3/mA/9HC0KVXw3cCPlVtsnbA/WW+E/AJqYYUhi69Gq4T8LmpEhJwv5jtBNwg1dDCsHV/h+kEfIhzdEw23f4Lpg2AC22VIAwV/UjRj7QB+EboNfBrS8GVntYA1KGN++ph+N8OyA7QaQOQNm/gAybdAR35Id7gDE0QhkB3QJe6AaC3HCqxA85huzX0DF25HTindcAhQYYSwjDtGtARJmCkmmQEzgnWgHQNQEUPw8Qp0PnSmx6AdAK1TpgC6RuA1cPwvHofcE4cgPQfVV1SB2xYPz0Mz0k6wXPiAKTfhHrZxgGHZLvI9DBMPAt0iQOQ3kK8OqemcsDbdrvIj/wKnXga7E4sdpHPyE8ldEBDu42aPkM04oBtACSu/+A7f8rBAW3iXWTvjzFwQOL637zBwcABKvEusvfHGDiAVj/+unlvbjBwQOrbqIT6UzsA//BpM1QDMHAAzwZgOwdoGn96AKZ3QJYNwFYOaNkG4IoOyLIBSO4APL1TByADB6RuAJC/vJkDuE/Asx3SOoDfBNze1G+MGZM6gHkAWmPMkNQBvCfg2SR3AO8AtA5AKgekqn+VAJxNegdwnoBnaz6UNgU4T8Dmoq37gBceDQDAhAFoEgHgMgFb86mejwPWO0iM/9hsvtQ/wQHnZwagq5+ZA1ao/z341qlx6pmsAZsG4GScBh4OWHECxj8VWBRAegd02wbgMoBxcwckn4Dx88cGAZDWAc/fAp4NMwdsfQ94YuKA87O2gC0vB7xvNAE7GcMgBZ7SALglgE8n+IR7wBMnB2zaALglgE8n+L5hADoDMEkBFAB9Al4wAKMUeN/8HuhssnPAg/XXsGCA3BxACUDcAD1wdwDybGhsbk7mVgNwdwApAPErALg74Ndjn7CFMAA9MHcArQHAl4CBuQN+0AIQXwJG3g4gNwB4CLJ2ADkAcQDA2QEJ6oep/wsAZwekOQVss3FAmvphymUNoAZgWBAe2e4HUCZgHACfe4PvCQIQBcBpT/A9vpDf3p3jMhyQ8hT0lIEDVpyA8VaIYwoQAhCVzWA/oCWcgo6+ADj2AZrQAOArYAb7AZoagLgBnEaWDjgnqh/MN40ZOYD+GNBsMnEAoX70CsggBTQ1APEMdBpyccAa9YP5rp6tA86EAPQuAfw7QU2ZgPErgP+9wS8AXVQA4pr6TwL87w5rwoswfLLjvwC4nxBxALqIAMTVQ6YOIAWA0zTO5o7YpsCl9lXqn69TIIPzAXrtAPyy+WRy7ATp9U8OQI6zQEMKwBEA/lQ5mxynweaR+v8t62j7z7LhCkAGJ0QwAHgA2h4sAFwu8ckLgP+OUBNfvzHGmv5oLwCsMWOBDtBhM88IYByALFOgiX4V5HQDYPqoMuc+oIkOQGucYDYOQIad4AKAH6HbHv1sbgDkOAs0cQF4W2Zvr20+m9ymwfu/QnWxe/++DZF+zM0B2ARs4wCYITMH1BpiAdymIP/zAX4AGiIAuK/4+AEgq13hLzWxE+D9Gvvxg0yO9wUapH4cgLnYfzYm/06wfmzz//Pbn4zJfz9APQbgaz88//2AAACTWVb+0yAZQIYnRNIBOB5Hy/KsMA2AjfruWZ4WTw/ArX4snxfYBgAId0APwh3QF+sAE6Zhd8DuANkOGKQ7YCzVAXMogFIdMEl3gJXuABMoKNQBUzCAMh0wm0D1hTpgNrIdMFsTqKFMB5hgQZkOiNgLLdMB4VeAdAeMRTrA2nAAJTpgNka2AyZjZDvAmnBBiQ6IANBDiQ6YTbCGIh0Ax+NxPApeA2IuhKFIB3xqku6ASW4fELMUFpkCEQD6MlMgfCCCgh0AQRkg3AFj0Q6wAStA0Q6wAfXLdsAAZTtgMojGwh2AAoDCHWDRJaBwB2AABukOGEt3gEEEhTtgRq+Awh2AAOihdAdMWP2lO2BC6i/eAdafAOU7wHoXQAEO8Cdg+Q6YvSuAAAd4AUhwgC8EBgkO8AEYJTjA+gBIcIAPAEhwgHcNlOAABMD4mRTDOA+FOmD2h8BsjgPAZHpb6FlhvwOGDz6DNR8q1QFgvBaYjDkW/swQAqD85wb9w7At/8lRBED5zw77GyEB7w+YvAAEPD0++xqhWYADYPYBEPEOkXkRwO31UaoDHAEEwFiqAxaTYAAr4j1CAPMiACEOWLDACDLeJLXYDIyzkeIAuA/AinHAUj8oxwFgDaqhZAeEPEg/FO2ADwSyHQAAk3AHwCzdASDdAbA7QLoDrHQHWOkOQM5Mlu+AaSMH/GiYApg3csB/TkwBQBCA2Y5EB7zCG1MANuDBgaMxA9UBAG/ZArCei6EKBwAHlgAmFMBsPACa4EvggwBHADMKwJqVHADnJkcAs1nHARcC/AAAtilonReoDgA4MQRgEQBue5TuAIC37ABY99/tUR1wIcAOgHFauk9wBCeiAwAOWQFw9ic7wBHgBWAOujsw29UcAOcmPwBHY0a6AxwBTgAmg6q3xgGgOwDgxAmANWEaqA64ESMAJkh0B2QPoFQHzNIdMJkwHaFQB1iD69IKF+oAG/r1l+qA0DcLluqAOWz9K9cBUxCAgh1gDarjCAU7wAat/wU7IGj9K9gBc2D9dAe88AQwUes/V6HSLAFYYv1wqIKlOQLYsP6q7vgBmIn1v1VVFAF2ACZq/XFS7ABYUv2nKlYtNwC0+psqWi0vABPlSYlzUz0gnQuAVE9MVpoTALOogRCAWBTwAeB5gpgQADgBNgAmzwpAqB+TYgNgOQTxAKRIsQcwoPXT1PIAMCNXABKAFLUsAEzIEojUT5LmAMA+aIBDRVetuT47jBvgZ7WG6o7p0+POAEgAUqW6hAASGuC9WkuK5ys0EAOcqvX0khAAPQLwCZiuNiEAugHwAKRLs3yPkKf+Q7WyNL//YiOuAaCHIbe3y4+RAUgnwOtlan1k/XQpVi9U7AkBSCGQHgC9BzxVqdRuBQC/AAZCABLUbgMAXwF7Qv0k6U0A4AYgBCBZ6QHgBhhCJ+DMAWAGwAMwcwDxK8Dv6lZ5A0AjEA/AvAFYs6DwAMgawHITzKt+MoD4KYhNAKYFYJbErH4qgPgumE8AJgGAXwHM6k8FwCyJUQCmAIBfAdzq3xrAyCgAnwGgZ1c/EUBsHzxwCsBnABhZTMDPA9CzCsAEALA2YOAxAW8EoP9OYWQVgCkBXL7t4zwezbWYBUA6AEd3uZsr9QzrTwJg6o2BewB4BWBCAK7WGwADw/qrukvhANvfe7H+yCsAHYG1ARxhuqr16ABwrN9VQQDglTMBswB0ZaQF4ExwewiKkdpt/ouNnlkAXqlNCcC1Bmzrd0USAOAmGJgF4G0UrA+A1T3gAAJrA+B1DxiX2gzAe8VTamUAvO4Bh6hdFQCze8BBauMBFFV/VemVALA6BBUlHQugsPqr+i0SQBEB6BEKQEL9XgCFBGBCAGwn4JUAFBOAGwDItn4vgHIC8EEAWU/AawAoPABjAfA6Bc0IQK4NQACAwgMQByChfi+AwgMQByChfi+AwgMQByChfi+AwgMQB1DqBBwMoPAAJAI45x8AKIDCAxAHUHoAoAAk1F8pD4DCA9CVuQRARP1V1S4CKDwAHYElAELqryq9AKDwALySvg9ATP1V3d0FUHgAXkt19wDkdAiKKnUPQPEBeK2XOwBKnYDvq/0OQEAAXuv1G4BSJ+Al6b8BSAjA2zD8C4CIALwlcAtAWv1VpW4BCAnARSnh9VdKTAAuSAmvv1JyAvC+VBGHoAhSkgLwnpTw+islNwAvUoID4FNKeP2VyvsUNF1KbAPwBUBwAHxKCa+/UnID8KJa8gK4a9euXbuerX8A9COrgrHS6MoAAAAASUVORK5CYII=",
      }

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: false
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
