[[header]]
name = "Whatâ€™s COVID-19?"
url = "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000164708_00079.html"
weight = 10

[[header]]
name = "How to Treat a Fever"
url = "https://www.pref.chiba.lg.jp/kenfuku/hatsunetsu.html"
weight = 20

[[header]]
name = "COVID-19 Info"
url = "https://www.city.ichikawa.lg.jp/catpage/kurashi-shingatacorona.html"
weight = 30

[[header]]
name = "Public Facilities Info"
url = "https://www.city.ichikawa.lg.jp/covic/declaration.html"
weight = 40

[[header]]
name = "Mayor Comments"
url = "https://www.city.ichikawa.lg.jp/new01/covid19_comment.html"
weight = 50

[[header]]
name = "City Official Website"
url = "https://www.city.ichikawa.lg.jp"
weight = 60

[[header]]
name = "About"
url = "/about/"
weight = 70

[[header]]
name = "Contact Form"
url = "https://forms.gle/A1a849XahuB9w7CH6"
weight = 80

[[header]]
name = "GitHub"
url = "https://github.com/Meiryo7743/covid-19-ichikawa/"
weight = 90
