name: Fetch Data (Test)

on:
  # schedule:
  #   - cron: "30 10 * * *" # At 19:30 JST every day
  push:
    branches:
      - "fix-issue#163"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Switch to development branch
      - uses: actions/checkout@v2
        # with:
        #   ref: development

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4
          pip install html5lib
          pip install lxml
          pip install python-dateutil
          pip install ruamel.yaml
      - name: Run scripts
        run: |
          python ./data_updater/fetch_patients.py;
          python ./data_updater/patients_details.py;
          python ./data_updater/patients_count.py;
          python ./data_updater/fetch_subway.py;
          python ./data_updater/subway_passengers.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data files" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          # branch: development
